name: Publish pre-release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish-lib:
    runs-on: ubuntu-latest
    name: Publish OpenAPI Diff Action tool to nuget
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - name: Setup nbgv
        uses: aarnott/nbgv@v0.3
      - name: Create the package
        run: dotnet pack --configuration Release
      - run: |
          dotnet --version
          dotnet nuget --version
      - name: Add GPR Source
        run: dotnet nuget add source https://nuget.pkg.github.com/yaos/index.json --name GPR --username fabich --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
      - name: Publish the package
        run: dotnet nuget push *.nupkg --skip-duplicate --source GPR --verbosity  detailed
        working-directory: ./src/yaos.OpenAPI.Diff/nupkg
