name: Publish pre-release

on:
  release:
    types: [published]

jobs:
  publish-lib:
    runs-on: ubuntu-latest
    name: Publish OpenAPI Diff Action tool to nuget
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          ref: ${{ GITHUB_REF }}
      - name: Setup .net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.201" # SDK Version to use.
      - name: Setup nbgv
        uses: aarnott/nbgv@v0.3
        id: nbgv
      - name: Create the package
        run: dotnet pack --configuration Release /p:PublicRelease=true
        working-directory: ./src/yaos.OpenAPI.Diff
      - name: Add GPR Source
        run: dotnet nuget add source https://nuget.pkg.github.com/yaos/index.json --name "GPR" --username fabich --password ${{ secrets.GPR_READ }} --store-password-in-clear-text
      - name: Publish the package to GPR
        run: dotnet nuget push *.nupkg --skip-duplicate --source "GPR"
        working-directory: ./src/yaos.OpenAPI.Diff/nupkg
      - name: Publish the package to NuGet
        run: dotnet nuget push *.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_AUTH_TOKEN_LIB}}
        working-directory: ./src/yaos.OpenAPI.Diff/nupkg
