name: Publish

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  publish-lib:
    runs-on: ubuntu-latest
    name: Publish OpenAPI Diff Action tool to nuget
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - name: Setup .net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.201" # SDK Version to use.
      - name: Setup nbgv
        uses: aarnott/nbgv@v0.3
        id: nbgv
      - name: Create the package
        run: dotnet pack --configuration Release /p:PublicRelease=true
        working-directory: ./src/yaos.OpenAPI.Diff
      # - name: Publish the package
      #   run: dotnet nuget push *.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_AUTH_TOKEN_LIB}}
      #   working-directory: ./src/yaos.OpenAPI.Diff/nupkg
