name: Publish pre-release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish-lib:
    runs-on: ubuntu-latest
    name: Publish OpenAPI Diff Action tool to nuget
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - name: Setup nbgv
        uses: aarnott/nbgv@v0.3
      - name: Create the package
        run: dotnet pack --configuration Release
        working-directory: ./src/yaos.OpenAPI.Diff
      - name: Setup nuget config
        run: sed 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' .nuget.config > nuget.config
      - name: Publish the package
        run: dotnet nuget push *.nupkg --skip-duplicate --source github
        working-directory: ./src/yaos.OpenAPI.Diff/nupkg
